/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import atendimento.ANIMAL;
import atendimento.CLIENTE;
import atendimento.FISICA;
import atendimento.JURIDICA;
import controller.cadastroController;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rotch
 */
public class cadastro extends javax.swing.JPanel {

    DefaultTableModel modelo;
    DefaultTableModel mAnimal;
    
    cadastroController cad;
    public cadastro(Map<Integer,CLIENTE> clientes,Map<Integer,ANIMAL> animais) {
        initComponents();
        
        cad = new cadastroController(clientes,animais);
        
        modelo = (DefaultTableModel) jTable1.getModel();
        mAnimal = (DefaultTableModel) jTable2.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        cTelefone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        aAltura = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        aFoto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cCpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cLogra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        cNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton2 = new javax.swing.JRadioButton();
        cComple = new javax.swing.JTextField();
        cName = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        aName = new javax.swing.JTextField();
        aData = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cBairro = new javax.swing.JTextField();
        aRaca = new javax.swing.JTextField();
        cMonicipio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aPeso = new javax.swing.JTextField();
        cEstado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(6, 56, 179));

        try {
            cTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefone");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Raça");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Peso");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Altura");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Foto");

        aFoto.setBackground(new java.awt.Color(20, 84, 207));
        aFoto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aFoto.setForeground(new java.awt.Color(255, 255, 255));
        aFoto.setText("Escolha o arquivo");
        aFoto.setBorder(null);
        aFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aFotoMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pessoa:");

        jRadioButton1.setBackground(new java.awt.Color(6, 56, 179));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Fisica");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logradouro");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número");

        jButton8.setBackground(new java.awt.Color(20, 84, 207));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Criar");
        jButton8.setBorder(null);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "nome", "Logradouro", "Número", "Complemento", "Bairro", "Municipío", "Estado", "pessoa", "Telefone", "cpf/cnpj"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jRadioButton2.setBackground(new java.awt.Color(6, 56, 179));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Juridica");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Data de Nascimento", "Raça", "Peso", "Altura"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("cpf/cnpj");

        jButton9.setBackground(new java.awt.Color(20, 84, 207));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Cancelar");
        jButton9.setBorder(null);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(20, 84, 207));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Criar");
        jButton11.setBorder(null);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(20, 84, 207));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Cancelar");
        jButton12.setBorder(null);
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(20, 84, 207));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Remover");
        jButton13.setBorder(null);
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        aData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data de Nascimeto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Complemento");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bairro");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Município");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado");

        jButton10.setBackground(new java.awt.Color(20, 84, 207));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Remover");
        jButton10.setBorder(null);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Cliente");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Pet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel18)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(cMonicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(64, 64, 64)
                                    .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(14, 14, 14)
                                        .addComponent(cNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cLogra, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cComple, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(10, 10, 10)
                                .addComponent(cCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(aName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aPeso))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel14)
                                .addGap(23, 23, 23)
                                .addComponent(aFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(aRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(aAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aData)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(0, 0, 0))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(cTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(aPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel15)
                            .addComponent(cCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(aData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cMonicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(cEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cComple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cLogra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(cNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(19, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(aRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(aAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(aFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    double contador = 0;
    int contAnimal = 0;
    int row = 0, rowAnimal = 0;
    boolean select = false,selectAnimal = false;
    byte[] fileContent = null;
    
    private void aFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aFotoMouseClicked
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.setCurrentDirectory(new java.io.File("."));
            FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
            chooser.setFileFilter(imageFilter);

            chooser.setAcceptAllFileFilterUsed(false);
            chooser.showOpenDialog(null);
            
            if(chooser.getSelectedFile() != null){
                
                fileContent = Files.readAllBytes(chooser.getSelectedFile().toPath());
            
            
               ImageIcon imageIcon = new ImageIcon(fileContent);
                jLabel17.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(119, 119, Image.SCALE_DEFAULT))); 
            }
            
        } catch (IOException ex) {
            //Logger.getLogger(secretaria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aFotoMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        //cName cLogra cNumero cComple cBairro cMonicipio cEstado cTelefone cCpf
        String pessoa = null;
        try{
            if(!cName.getText().equals("") && !cLogra.getText().equals("") && !cNumero.getText().equals("") && !cComple.getText().equals("") && !cBairro.getText().equals("") && !cMonicipio.getText().equals("") && !cEstado.getText().equals("") && !cTelefone.getText().equals("") && !cCpf.getText().equals("")){
                if(select){
                    int id = (int)((double)modelo.getValueAt(row, 0)) ;
                    if(jRadioButton1.isSelected()){
                        pessoa = "fisica";
                        cad.add(id, new FISICA((String)cCpf.getText(),
                            id,
                            (String)cName.getText(),
                            (String)cLogra.getText(),
                            Integer.parseInt(cNumero.getText()),
                            (String)cComple.getText(),
                            (String)cBairro.getText(),
                            (String)cMonicipio.getText(),
                            (String)cEstado.getText(),
                            (String)cTelefone.getText(),
                            getAnimais()));
                    }
                    else if(jRadioButton2.isSelected()){
                        pessoa = "juridica";
                        cad.add(id, new JURIDICA((String)cCpf.getText(),
                            id,
                            (String)cName.getText(),
                            (String)cLogra.getText(),
                            Integer.parseInt(cNumero.getText()),
                            (String)cComple.getText(),
                            (String)cBairro.getText(),
                            (String)cMonicipio.getText(),
                            (String)cEstado.getText(),
                            (String)cTelefone.getText(),
                            getAnimais()));
                    }
     
                            upColCli(cad.get(id));
                        limparCliente();
                }else{  
                    if(jRadioButton1.isSelected()){
                        pessoa = "fisica";
                        cad.add((int)contador, new FISICA((String)cCpf.getText(),
                            contador,
                            (String)cName.getText(),
                            (String)cLogra.getText(),
                            Integer.parseInt(cNumero.getText()),
                            (String)cComple.getText(),
                            (String)cBairro.getText(),
                            (String)cMonicipio.getText(),
                            (String)cEstado.getText(),
                            (String)cTelefone.getText(),
                            getAnimais()));
                    }
                    else if(jRadioButton2.isSelected()){
                        pessoa = "juridica";
                        cad.add((int)contador, new JURIDICA((String)cCpf.getText(),
                            contador,
                            (String)cName.getText(),
                            (String)cLogra.getText(),
                            Integer.parseInt(cNumero.getText()),
                            (String)cComple.getText(),
                            (String)cBairro.getText(),
                            (String)cMonicipio.getText(),
                            (String)cEstado.getText(),
                            (String)cTelefone.getText(),
                            getAnimais()));
                    }
                    modelo.insertRow(modelo.getRowCount(), new Object[]{contador,
                        (String)cName.getText(),
                        (String)cLogra.getText(),
                        (String)cNumero.getText(),
                        (String)cComple.getText(),
                        (String)cBairro.getText(),
                        (String)cMonicipio.getText(),
                        (String)cEstado.getText(),
                        (String)cTelefone.getText(),
                        pessoa,(String)cCpf.getText()});
                    contador++;
                    limparCliente();
                }
            }else{
                JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!");
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(jTable1.getRowCount() > 0){
        row = jTable1.rowAtPoint(evt.getPoint());
        int id = (int)((double) modelo.getValueAt(row, 0));
        
        inputCli(cad.get(id));
        
        mAnimal.setRowCount(0);
        for(ANIMAL a : cad.get(id).getAnimais()){
            mAnimal.insertRow(mAnimal.getRowCount(), new Object[]{Integer.toString(a.getId()),
                (String)a.getNome(),
                (String)a.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                (String)a.getRaca(),
                Float.toString(a.getPeso()),
                Float.toString(a.getAltura())});
        }
        select = true;
        change();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void upColCli(CLIENTE cliente){
                    int id = (int)((double)modelo.getValueAt(row, 0));
                    modelo.setValueAt((String)cliente.getNome(), row, 1);
                    modelo.setValueAt((String)cliente.getLogradouro(), row, 2);
                    modelo.setValueAt(Integer.toString(cliente.getNumero()), row, 3);
                    modelo.setValueAt((String)cliente.getComplemento(), row, 4);
                    modelo.setValueAt((String)cliente.getBairro(), row, 5);
                    modelo.setValueAt((String)cliente.getMunicipio(), row, 6);
                    modelo.setValueAt((String)cliente.getEstado(), row, 7);
                    modelo.setValueAt((String)cliente.getTelefone(), row, 8);
                    
                    if(cliente instanceof FISICA){
                        modelo.setValueAt("fisica", row, 9);
                        modelo.setValueAt((String)((FISICA) cliente).getCnpj(), row, 10);
                    }else{
                        modelo.setValueAt("juridica", row, 9);
                        modelo.setValueAt((String)((JURIDICA) cliente).getCnpj(), row, 10);
                    }
    }
    private void inputCli(CLIENTE cliente){
        cName.setText((String)cliente.getNome());
        cLogra.setText((String)cliente.getLogradouro());
        cNumero.setText(Integer.toString(cliente.getNumero()));
        cComple.setText((String)cliente.getComplemento());
        cBairro.setText((String)cliente.getBairro());
        cMonicipio.setText((String)cliente.getMunicipio());
        cEstado.setText((String)cliente.getEstado());
        cTelefone.setText((String)cliente.getTelefone());
        
        
        if(cliente instanceof FISICA){
                        cCpf.setText((String)((FISICA) cliente).getCnpj());
                        jRadioButton1.setSelected(true);
                    }else{
                        cCpf.setText((String)((JURIDICA)cliente).getCnpj());
                        jRadioButton2.setSelected(true);
                    }
    }
    
   private void upColAni(ANIMAL animal){
                        mAnimal.setValueAt((String)animal.getNome(), rowAnimal, 1);
                        mAnimal.setValueAt(animal.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), rowAnimal, 2);
                        mAnimal.setValueAt((String)animal.getRaca(), rowAnimal, 3);
                        mAnimal.setValueAt(Float.toString(animal.getPeso()), rowAnimal, 4);
                        mAnimal.setValueAt(Float.toString(animal.getAltura()), rowAnimal, 5);
    }
   
    private void inputAni(ANIMAL animal){
        aName.setText((String)animal.getNome());
        aData.setText(animal.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        aRaca.setText((String)animal.getRaca());
        aPeso.setText(Float.toString(animal.getPeso()));
        aAltura.setText(Float.toString(animal.getAltura()));
    }
    
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        if(jTable2.getRowCount() > 0){
            rowAnimal = jTable2.rowAtPoint(evt.getPoint());
            
            int id = Integer.parseInt((String)mAnimal.getValueAt(rowAnimal, 0));
            
            if(cad.getAni(id).getFoto() != null){
                
                ImageIcon imageIcon = new ImageIcon(cad.getAni(id).getFoto());
                jLabel17.setIcon(new ImageIcon(imageIcon.getImage().getScaledInstance(119, 119, Image.SCALE_DEFAULT))); 
                
            }
            
            inputAni(cad.getAni(Integer.parseInt((String)mAnimal.getValueAt(rowAnimal, 0)) ));
            selectAnimal = true;
            changeAni();
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        limparCliente();
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        try{
            if(!aName.getText().equals("") && !aData.getText().equals("") && !aRaca.getText().equals("") && !aPeso.getText().equals("") && !aAltura.getText().equals("")){
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                LocalDate nascimento = LocalDate.parse(aData.getText(), formatter);
                    if(selectAnimal){
                        int id = Integer.parseInt((String)mAnimal.getValueAt(rowAnimal, 0));
                        
                            cad.addAni(id, new ANIMAL(id,
                                (String)aName.getText(),
                                nascimento,
                                (String)aRaca.getText(),
                                Float.parseFloat(aPeso.getText()),
                                Float.parseFloat(aAltura.getText()),
                                fileContent));
                            
                            upColAni(cad.getAni(id));
                            if(select){
                                int cId = (int)((double)modelo.getValueAt(row, 0));
                                cad.setCliAni(cId,getAnimais());
                            }
                        limparAnimal();
                    }else{
                        cad.addAni(contAnimal, new ANIMAL(contAnimal,
                                (String)aName.getText(),
                                nascimento,
                                (String)aRaca.getText(),
                                Float.parseFloat(aPeso.getText()),
                                Float.parseFloat(aAltura.getText()),
                                fileContent));
                        
                        mAnimal.insertRow(mAnimal.getRowCount(), new Object[]{Integer.toString(contAnimal),
                            (String)aName.getText(),
                            (String)aData.getText(),
                            (String)aRaca.getText(),
                            (String)aPeso.getText(),
                            (String)aAltura.getText()});
                        
                        contAnimal++;
                        if(select){
                                int cId = (int)((double)modelo.getValueAt(row, 0));
                                cad.setCliAni(cId,getAnimais());
                            }
                        limparAnimal();
                        //aName aData aRaca aPeso aAltura afoto
                    }
            }else{
                JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar!");
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        limparAnimal();
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        if(selectAnimal){
            //cad.delAni(Integer.parseInt((String)mAnimal.getValueAt(rowAnimal, 0)));
            mAnimal.removeRow(rowAnimal);
            limparAnimal();
        }
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        if(select){
            cad.delcli((int)((double)modelo.getValueAt(row, 0)));
            modelo.removeRow(row);
            limparCliente();
        }
    }//GEN-LAST:event_jButton10MouseClicked
    
    ANIMAL[] getAnimais(){
        ANIMAL[] newAnimal = new ANIMAL[mAnimal.getRowCount()];
        for (int i = 0; i < mAnimal.getRowCount(); i++) {
            newAnimal[i] = cad.getAni(Integer.parseInt((String)mAnimal.getValueAt(i, 0)));
        }
        return newAnimal;
    }
    void limparCliente(){ 
        cName.setText("");
        cLogra.setText("");
        cNumero.setText("");
        cComple.setText("");
        cBairro.setText("");
        cMonicipio.setText("");
        cEstado.setText("");
        cTelefone.setText("");
        cCpf.setText("");
        select = false;
        make();
        mAnimal.setRowCount(0);
    }
    
    void limparAnimal(){
        jLabel17.setIcon(null);
        
        aName.setText("");
        aData.setText("");
        aRaca.setText("");
        aPeso.setText("");
        aAltura.setText("");
        selectAnimal = false;
        makeAni();
    }

    void make(){
    jButton8.setText("Criar");
}
void change(){
    jButton8.setText("Alterar");
}
    void makeAni(){
    jButton11.setText("Criar");
}
void changeAni(){
    jButton11.setText("Alterar");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aAltura;
    private javax.swing.JFormattedTextField aData;
    private javax.swing.JButton aFoto;
    private javax.swing.JTextField aName;
    private javax.swing.JTextField aPeso;
    private javax.swing.JTextField aRaca;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cBairro;
    private javax.swing.JTextField cComple;
    private javax.swing.JTextField cCpf;
    private javax.swing.JTextField cEstado;
    private javax.swing.JTextField cLogra;
    private javax.swing.JTextField cMonicipio;
    private javax.swing.JTextField cName;
    private javax.swing.JTextField cNumero;
    private javax.swing.JFormattedTextField cTelefone;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
